# ===================================================================
# This is a sample YAML-formatted CloudFormation template.
# ===================================================================
AWSTemplateFormatVersion: 2010-09-09
Description: Single instance template with parameters

# ===================================================================
# Parameters
# ===================================================================
Parameters:

  ImageId:
    Type: String
    Description: Image ID of instance
    Default: ami-14c5486b

  InstanceType:
    Type: String
    Description: Instance type of instance
    Default: t2.large
    AllowedValues: 
      - t2.micro
      - t2.large
      - m1.small
      - m1.large

# ===================================================================
# Resources
# ===================================================================
Resources:

  SingleInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      Tags:
      - Key: Name
        Value: Single Instance

